# Generated by Django 5.1.1 on 2024-09-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='landingpage.service', verbose_name='Serviço'),
        ),
    ]
